### ISSUE TITLE
Error occured - Error during rendering report: Error during rendering report: undefined

### ISSUE THREAD

**Issue by ABoudreault94** [jsreport/jsreport-pdf-utils#1]
Im trying to use pdf-utils to apply watermarking to my phantom-pdf report but it looks like it doesn't work when im using the header or footer section. 

Theres an example with a header content [< p >test< /p >] :
https://playground.jsreport.net/studio/workspace/ByNep1f_G/6

If I remove it, it work...

**Comment by pofider** [comment]
Yes, thank you. I can confirm this as bug.

You should be able to use another merge operation to add header instead of using the phantom native one until we solve it.
https://playground.jsreport.net/studio/workspace/ByNep1f_G/8

**Comment by pofider** [comment]
After phantomjs project archivation, we stop investing time also in this extension here.
