### ISSUE TITLE
Support TOC

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-pdf-utils#15]
Including page numbers and outlines.

**Comment by pofider** [comment]
This is now ready.

Installation...
```
npm i jsreport/jsreport-pdf-utils
```

How it works... 
I updated the pdf utils extension in playground and prepared demo with TOC. 
You can find it here
https://playground.jsreport.net/w/jan_blaha/fSeLP90e

The idea is the following. The chrome-pdf already supports rendering pdf links. What was missing is adding page numbers to the TOC and also adding outlines to the final pdf. The page numbers are merged to the TOC using stadnard pdf utils merge operation and page items feature. The outlines can developer specify using the html and anchor attribute ` data-pdf-utils-outline`.

I would love to get some feedback and comments.

**Comment by hansip** [comment]
Awesome, we'll check it out. Thanks @pofider :)

**Comment by hansip** [comment]
The solution looks good @pofider 👍

**Comment by joshplaetzler** [comment]
@pofider This is a great solution I'm hoping to get away from wkhtmltopdf in production.  Any idea when this update will be officially released?

**Comment by bjrmatos** [comment]
> @pofider This is a great solution I'm hoping to get away from wkhtmltopdf in production. Any idea when this update will be officially released?

this is realased in 1.3.0, it will part of official jsreport soon. if you need right now, just run `npm install jsreport-pdf-utils@1.3.0` on your project
