### ISSUE TITLE
Append | Prepend pdf files using jsreport API

### ISSUE THREAD

**Issue by Sahil333** [jsreport/jsreport-pdf-utils#21]
How can i append or prepend already generated pdf files through jsreport API? I have a set of pdf files in the cloud storage and I want to merge all those files into one pdf and upload it back to the cloud.

**Comment by pofider** [comment]
Closing this in favour of duplicate created on our forum. I respond there when I find some time.
https://forum.jsreport.net/topic/1328/concatenate-external-pdfs-into-one-pdf
