### ISSUE TITLE
pdfAddPageItem helper not included when recipe is not PDF

### ISSUE THREAD

**Issue by OlivierKamers** [jsreport/jsreport-pdf-utils#22]
I updated to version 1.6.0 and noticed that when using an html recipe the pdfAddPageItem helper is no longer included. 

The change is made in this commit: https://github.com/jsreport/jsreport-pdf-utils/commit/0286dbaed3bf099dc674f0ed50406ee642a79a77 but from the description and test I would expect that it would be added as a helper? It seems that the difference is that in the test case the parent template uses PDF recipe and the child template doesn't. In my test case no templates use the PDF recipe.

We generate html just for some testing purposes so I can work around it for now but I'd like to understand what I'm doing wrong here.

**Comment by pofider** [comment]
Thank you for the issue. Question...

Do you care if these pdf utils helpers return something when executed from the html recipe or it can be just dummy helper in this case? These helpers currently return some span elements that are later parsed from the pdf.

**Comment by OlivierKamers** [comment]
For our testing purposes it's not important that they return something valid. I've currently implemented a fix by adding an empty function as fallback like this: 
```ts
req.template.helpers.pdfAddPageItem = req.template.helpers.pdfAddPageItem || ((): void => { });
```
