### ISSUE TITLE
Add data parameter

### ISSUE THREAD

**Issue by developerscontinusys** [jsreport/jsreport-pdf-utils#24]
Allow own data on pdf utils.
example on api
`{
    'template': {...},
    'data': [1, 2, 3],
}`

This will be good when we will try to build reports on the fly with different layout and data per pdf

**Comment by pofider** [comment]
Thank you for the suggestion.

You mean here right?
```js
{
  "template": {
       ...,
       "pdfOperations": [{
           "template": {
               ...
            },
            "type": "merge" 
           /*** here ****/
            "data": { ... }
        }]
   },
  "data": { ... }
}
```

It seems this isn't necessary. The pdf operation gets the data from the parent template.
This means you can put the required data to the parent and just access it.
Like this.

```js
{
  "template": {
       ...,
       "pdfOperations": [{
           "template": {
               ...
               "content": "{{somethingForMerge}}"
            },
            "type": "merge"           
        }]
   },
  "data": { 
      ... 
      "somethingForMerge": "foo"
  }
}
```

**Comment by developerscontinusys** [comment]
Yah. What I wanted is I have a list of templates which I'm trying to combined into one list of reports. Some reports have different sets of data and designs like this one
https://playground.jsreport.net/w/admin/6wQ6JyNp

```
{
  "template": {
       ...,
       "pdfOperations": [{
           "template": {
               ...
               "content": "{{somethingForMerge}}",
            },
            "type": "merge",
            "data": {"utildata": "foo"}           
        }]
   },
  "data": { 
      ... 
      "somethingForMerge": "foo"
  }
}
```

**Comment by pofider** [comment]
I apologize this was laying here for such a long time.
We got opened a duplicated issue so I close this one in favor of 
https://github.com/jsreport/jsreport/issues/775

We proposed a solution there which can be used already if someone is interested.
