### ISSUE TITLE
Update node-signpdf version

### ISSUE THREAD

**Issue by lichutin-st** [jsreport/jsreport-pdf-utils#26]
Hello!

Current version of "node-signpdf" refers to vulnerable "node-forge" version.
Can you change it to avoid vulnerabilities?

Screen from `npm audit`

![изображение](https://user-images.githubusercontent.com/68215827/94784210-84278800-03d6-11eb-953e-caaed5600ad1.png)

**Comment by pofider** [comment]
Hi, we will update this dep during the next release.
Please see the notes how we handle vulnerabilities here https://github.com/jsreport/jsreport#vulnerabilities
