### ISSUE TITLE
PDF form elements (pdfFormField)

### ISSUE THREAD

**Issue by mohamadserawan** [jsreport/jsreport-pdf-utils#27]
I am trying to render the following template:

```<!DOCTYPE html>
<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
</head>
<body>
    {{{pdfFormField name='test' type='signature' width='100px' height='50px'}}}
    <div>
        <label>Name</label>
        {{{pdfFormField name='name' type='text' width='130px' height='40px'}}}
    </div>
    <div>
        <label>Surname</label>
        {{{pdfFormField name='surname' type='text' width='130px' height='40px'}}}
    </div>
</body>
</html>
```
And I got the excpeted pdf
![image](https://user-images.githubusercontent.com/2920551/95490590-144e6a00-09a1-11eb-91bf-42ddd6d0210a.png)

But when I am trying to add any Turkish character (Şş Çç Ğğ Üü Öö İi Iı) like:
```
<!DOCTYPE html>
<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
</head>
<body>
    <div>
        Şş Çç Ğğ Üü Öö İi Iı
    </div>
    {{{pdfFormField name='test' type='signature' width='100px' height='50px'}}}
    <div>
        <label>Name</label>
        {{{pdfFormField name='name' type='text' width='130px' height='40px'}}}
    </div>
    <div>
        <label>Surname</label>
        {{{pdfFormField name='surname' type='text' width='130px' height='40px'}}}
    </div>
</body>
</html>
```
I am gotting the following:
![image](https://user-images.githubusercontent.com/2920551/95490924-9dfe3780-09a1-11eb-9bb5-39d9ccae5567.png)

As you see the pdf is corrupted and if you zoom in you can find the following strings in the file
``fo rm@@``
``o rm@@``
``fo rm@@``

By the way this problem is only when I place the Turkish characters befor pdfFormField elements, I mean that if you try to change the position of the first div and put it at the end of the file, the generated pdf will be as expected without any rendering problem.

Template properties:
engine: handlebars
recipe: chrome-pdf (i tried to use phantom-pdf but it has the same problem)

Jsreport version: 2.10.0
jsreport-pdf-utils version: 1.9.0

**Comment by pofider** [comment]
Thank you for the bug report.
I pushed the [fix](https://github.com/jsreport/jsreport-pdf-utils/commit/192b69ea217b4979e04fdd1ec87eadce40ea4064).
Please try the report from the master
```
npm i jsreport/jsreport-pdf-utils
```

**Comment by mohamadserawan** [comment]
You are great :)

**Comment by mohamadserawan** [comment]
Hi again,
I have a problem in positioning of pdfFormField elements when I am trying to add margin top and bottom to template.


<img width="1104" alt="error" src="https://user-images.githubusercontent.com/2920551/97079518-3c72d580-15fd-11eb-8fa5-3b02c8050605.png">

**Comment by pofider** [comment]
Yes, I see the same. Thank you. I am looking into it.

**Comment by pofider** [comment]
please update the extension from git master again, and let me know if it fixes the problem, thank you.

**Comment by mohamadserawan** [comment]
[test.pdf](https://github.com/jsreport/jsreport-pdf-utils/files/5440039/test.pdf)

it is working ok for one page documents but unfortunately elements has been disappeared for multiple pages documents.
```
<!DOCTYPE html>
<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
</head>
<body>
    page 1
    <div style="page-break-after: always;"></div>
    page 2
    <div>
        Şş Çç Ğğ Üü Öö İi Iı
    </div>
    {{{pdfFormField name='test' type='signature' width='100px' height='50px'}}}
    <div>
        <label>Name</label>
        {{{pdfFormField name='name' type='text' width='130px' height='40px'}}}
    </div>
    <div>
        <label>Surname</label>
        {{{pdfFormField name='surname' type='text' width='130px' height='40px'}}}
    </div>
</body>
</html>
```

**Comment by pofider** [comment]
Thank you for your example. Please update the dep from git and give it another try.

**Comment by mohamadserawan** [comment]
Thanks for quick reply, there was no problem in positioning unless I have tried to enable "display header/footer" checkbox from chrome-pdf option panel.

![image](https://user-images.githubusercontent.com/2920551/97480748-e8e9ea00-1964-11eb-926a-b87c97da815d.png)

**Comment by pofider** [comment]
I see, thanks. Never-ending story here. It should be fixed now, please update again.

**Comment by mohamadserawan** [comment]
Thank you very much, now i can die in peace :)

**Comment by shubhamsWEB** [comment]
I am trying to render pdfFormField in multipage PDF but formField elements has been disappeared for multiple pages in the generated PDF. And this is happening randomly if i'm generating another PDF then some other formField elements are disappeared.
HELP!! @pofider

**Comment by pofider** [comment]
@shubhamsWEB Do you have the latest pdf utils? If yes, please create a separate bug report and include a minimal example replicating the problem.

**Comment by shubhamsWEB** [comment]
@pofider Thanks for quick response, it is working now, I was only using jsreport-phantom-pdf. 😅
