### ISSUE TITLE
Pdf created with pdf utils opens as blank page on Mac Safari

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-pdf-utils#3]
The simple example which fails to open.

https://playground.jsreport.net/studio/workspace/BkEHf9MNG/11

The Acrobat and Chrome works. The pdf validation is ok.

**Comment by pofider** [comment]
I've changed the implementation to always compress inner pdf streams. My guess is that this will make safari happy. Can someone with mac try it out on this pdf?
[out.pdf](https://github.com/jsreport/jsreport-pdf-utils/files/1821768/out.pdf)

**Comment by bjrmatos** [comment]
it works now in Safari and OSX desktop preview. good job 👌

**Comment by pofider** [comment]
Great. Thanks. Sorry for disrupting the weekend.

**Comment by bjrmatos** [comment]
all good. happy to help 😄

**Comment by pofider** [comment]
This change is now released in 0.5.0.
