### ISSUE TITLE
pdf language meta data

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport-pdf-utils#33]
Is it possible to backport this feature https://github.com/jsreport/jsreport/commit/571268ba3d66a3fa25178f7c93f918cc7e27e170#diff-bf2c483ee5a44c6bd1fe3d09bcc2e0900dce44a6b2470237d8639364b2554430 to v2.x.x?

**Comment by pofider** [comment]
I apologize but we are a bit overwhelmed.
If you need that feature in v2 please fork this repo and apply the changes you need.
