### ISSUE TITLE
Allow 'caching' of PDF's when used as header/footer

### ISSUE THREAD

**Issue by yoerivdm** [jsreport/jsreport-pdf-utils#5]
I add a static header / footer, I noticed that every PDF-script operation re-renders each added PDF. If no script is involved (like page numbers etc), they should only be rendered once ... for the moment we gat a prformance hit by rendering 11 header PDF and 11 content pdf's :-)

We could see it as a separate PDF like described in another issue... with the difference that header. footer pdf's are generated by JSReport.

**Comment by pofider** [comment]
You mean to render header pdf once and reuse it over multiple separate pdf reports? 
Or render header pdf once and reuse it over every page in the output pdf?

**Comment by yoerivdm** [comment]
The latter .

**Comment by pofider** [comment]
It actually works like that if you uncheck "render for every page" in the operations list.

https://jsreport.net/learn/pdf-utils

**Comment by yoerivdm** [comment]
Damn, looked over that ... great! Thanks.

**Comment by pofider** [comment]
You are welcome.
